"""Add OAuth tables

Revision ID: 001dada1978d
Revises: ff398425d4eb
Create Date: 2026-01-28 12:02:05.324601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001dada1978d'
down_revision = 'ff398425d4eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_clients',
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('client_name', sa.String(length=64), nullable=False),
    sa.Column('redirect_uris', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('oauth_auth_codes',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_auth_codes')
    op.drop_table('oauth_clients')
    # ### end Alembic commands ###
