"""Add MFA fields

Revision ID: 2f7bf372e527
Revises: de34e3b33c59
Create Date: 2026-01-28 11:40:57.654843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7bf372e527'
down_revision = 'de34e3b33c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('is_mfa_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_mfa_enabled')
        batch_op.drop_column('mfa_secret')

    # ### end Alembic commands ###
