"""Add recovery codes and email otp

Revision ID: 86ead5bdaedd
Revises: 2f7bf372e527
Create Date: 2026-01-28 11:45:14.761351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ead5bdaedd'
down_revision = '2f7bf372e527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_otp_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('email_otp_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_otp_expires_at')
        batch_op.drop_column('email_otp_hash')

    # ### end Alembic commands ###
